---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: camelk-operatorgroup
  namespace: amq-streams-integration
spec:
  targetNamespaces:
  - amq-streams-integration
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: red-hat-camel-k
  namespace: amq-streams-integration
spec:
  channel: 1.4.x
  installPlanApproval: Automatic
  name: red-hat-camel-k
  source: redhat-operators
  sourceNamespace: amq-streams-integration